name: /Users/ananyasachdev/college/btp/RAG/ragenv
channels:
  - conda-forge
dependencies:
  - beautifulsoup4=4.13.4=pyha770c72_0
  - brotli-python=1.1.0=py310hb4ad77e_2
  - bzip2=1.0.8=h99b78c6_7
  - ca-certificates=2025.4.26=hbd8a1cb_0
  - certifi=2025.1.31=pyhd8ed1ab_0
  - cffi=1.17.1=py310h497396d_0
  - charset-normalizer=3.4.1=pyhd8ed1ab_0
  - faiss=1.9.0=py310h2dd55c0_0_cpu
  - faiss-cpu=1.9.0=hd610c6a_0
  - h2=4.2.0=pyhd8ed1ab_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - idna=3.10=pyhd8ed1ab_1
  - libblas=3.9.0=31_h10e41b3_openblas
  - libcblas=3.9.0=31_hb3479ef_openblas
  - libcxx=20.1.3=ha82da77_0
  - libexpat=2.7.0=h286801f_0
  - libfaiss=1.9.0=h682f5e0_0_cpu
  - libffi=3.4.6=h1da3d7d_1
  - libgfortran=14.2.0=heb5dd2a_105
  - libgfortran5=14.2.0=h2c44a93_105
  - liblapack=3.9.0=31_hc9a63f6_openblas
  - liblzma=5.8.1=h39f12f2_0
  - libopenblas=0.3.29=openmp_hf332438_0
  - libsqlite=3.49.1=h3f77e49_2
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=20.1.3=hdb05f8b_0
  - ncurses=6.5=h5e97a16_3
  - numpy=1.26.4=py310hd45542a_0
  - openssl=3.5.0=h81ee809_0
  - packaging=25.0=pyh29332c3_1
  - pip=25.1=pyh8b19718_0
  - pycparser=2.22=pyh29332c3_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.10.17=h6cefb37_0_cpython
  - python_abi=3.10=7_cp310
  - readline=8.2=h1d1bf99_2
  - requests=2.32.3=pyhd8ed1ab_1
  - setuptools=79.0.1=pyhff2d567_0
  - soupsieve=2.5=pyhd8ed1ab_1
  - tk=8.6.13=h5083fa2_1
  - typing-extensions=4.13.2=h0e9735f_0
  - typing_extensions=4.13.2=pyh29332c3_0
  - tzdata=2025b=h78e105d_0
  - urllib3=2.4.0=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - zstandard=0.23.0=py310h078409c_2
  - pip:
      - annotated-types==0.7.0
      - anyio==4.9.0
      - distro==1.9.0
      - exceptiongroup==1.2.2
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - jiter==0.9.0
      - openai==1.76.2
      - pydantic==2.11.4
      - pydantic-core==2.33.2
      - pymupdf==1.25.5
      - sniffio==1.3.1
      - tqdm==4.67.1
      - typing-inspection==0.4.0
prefix: /Users/ananyasachdev/college/btp/RAG/ragenv
